import { Country, City, TimeSlot, Seat, SharedCab, SharedVehicleType } from './models/booking.model';

export const COUNTRIES: Country[] = [
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'AE', name: 'UAE', flag: '🇦🇪' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
];

export const CITIES: City[] = [
  // India
  { id: 1, name: 'Mumbai', state: 'Maharashtra', flag: '🇮🇳', country: 'IN' },
  { id: 2, name: 'Delhi', state: 'NCR', flag: '🇮🇳', country: 'IN' },
  { id: 3, name: 'Bangalore', state: 'Karnataka', flag: '🇮🇳', country: 'IN' },
  { id: 4, name: 'Chennai', state: 'Tamil Nadu', flag: '🇮🇳', country: 'IN' },
  { id: 5, name: 'Hyderabad', state: 'Telangana', flag: '🇮🇳', country: 'IN' },
  { id: 6, name: 'Kolkata', state: 'West Bengal', flag: '🇮🇳', country: 'IN' },
  { id: 7, name: 'Pune', state: 'Maharashtra', flag: '🇮🇳', country: 'IN' },
  { id: 8, name: 'Ahmedabad', state: 'Gujarat', flag: '🇮🇳', country: 'IN' },
  { id: 9, name: 'Jaipur', state: 'Rajasthan', flag: '🇮🇳', country: 'IN' },
  { id: 10, name: 'Surat', state: 'Gujarat', flag: '🇮🇳', country: 'IN' },
  { id: 11, name: 'Lucknow', state: 'Uttar Pradesh', flag: '🇮🇳', country: 'IN' },
  { id: 12, name: 'Goa', state: 'Goa', flag: '🇮🇳', country: 'IN' },
  { id: 13, name: 'Kochi', state: 'Kerala', flag: '🇮🇳', country: 'IN' },
  { id: 14, name: 'Chandigarh', state: 'Punjab', flag: '🇮🇳', country: 'IN' },
  { id: 15, name: 'Bhopal', state: 'Madhya Pradesh', flag: '🇮🇳', country: 'IN' },
  // USA
  { id: 16, name: 'New York', state: 'New York', flag: '🇺🇸', country: 'US' },
  { id: 17, name: 'Los Angeles', state: 'California', flag: '🇺🇸', country: 'US' },
  { id: 18, name: 'Chicago', state: 'Illinois', flag: '🇺🇸', country: 'US' },
  { id: 19, name: 'Houston', state: 'Texas', flag: '🇺🇸', country: 'US' },
  { id: 20, name: 'San Francisco', state: 'California', flag: '🇺🇸', country: 'US' },
  // UK
  { id: 21, name: 'London', state: 'England', flag: '🇬🇧', country: 'GB' },
  { id: 22, name: 'Manchester', state: 'England', flag: '🇬🇧', country: 'GB' },
  { id: 23, name: 'Birmingham', state: 'England', flag: '🇬🇧', country: 'GB' },
  { id: 24, name: 'Edinburgh', state: 'Scotland', flag: '🇬🇧', country: 'GB' },
  // UAE
  { id: 25, name: 'Dubai', state: 'Dubai', flag: '🇦🇪', country: 'AE' },
  { id: 26, name: 'Abu Dhabi', state: 'Abu Dhabi', flag: '🇦🇪', country: 'AE' },
  { id: 27, name: 'Sharjah', state: 'Sharjah', flag: '🇦🇪', country: 'AE' },
  // Singapore
  { id: 28, name: 'Singapore', state: 'Central', flag: '🇸🇬', country: 'SG' },
  { id: 29, name: 'Jurong', state: 'West Region', flag: '🇸🇬', country: 'SG' },
  // Australia
  { id: 30, name: 'Sydney', state: 'New South Wales', flag: '🇦🇺', country: 'AU' },
  { id: 31, name: 'Melbourne', state: 'Victoria', flag: '🇦🇺', country: 'AU' },
  { id: 32, name: 'Brisbane', state: 'Queensland', flag: '🇦🇺', country: 'AU' },
  // Canada
  { id: 33, name: 'Toronto', state: 'Ontario', flag: '🇨🇦', country: 'CA' },
  { id: 34, name: 'Vancouver', state: 'BC', flag: '🇨🇦', country: 'CA' },
  { id: 35, name: 'Montreal', state: 'Quebec', flag: '🇨🇦', country: 'CA' },
  // Germany
  { id: 36, name: 'Berlin', state: 'Berlin', flag: '🇩🇪', country: 'DE' },
  { id: 37, name: 'Munich', state: 'Bavaria', flag: '🇩🇪', country: 'DE' },
  { id: 38, name: 'Frankfurt', state: 'Hesse', flag: '🇩🇪', country: 'DE' },
  // France
  { id: 39, name: 'Paris', state: 'Île-de-France', flag: '🇫🇷', country: 'FR' },
  { id: 40, name: 'Lyon', state: 'Auvergne', flag: '🇫🇷', country: 'FR' },
  { id: 41, name: 'Marseille', state: 'PACA', flag: '🇫🇷', country: 'FR' },
  // Japan
  { id: 42, name: 'Tokyo', state: 'Tokyo', flag: '🇯🇵', country: 'JP' },
  { id: 43, name: 'Osaka', state: 'Osaka', flag: '🇯🇵', country: 'JP' },
  { id: 44, name: 'Kyoto', state: 'Kyoto', flag: '🇯🇵', country: 'JP' },
];

export const TIME_SLOTS: TimeSlot[] = [
  { label: 'Early Morning', time: '06:00 AM', icon: 'bi-sunrise-fill' },
  { label: 'Morning', time: '09:00 AM', icon: 'bi-sun-fill' },
  { label: 'Noon', time: '12:00 PM', icon: 'bi-brightness-high-fill' },
  { label: 'Afternoon', time: '03:00 PM', icon: 'bi-sun' },
  { label: 'Evening', time: '06:00 PM', icon: 'bi-sunset-fill' },
  { label: 'Night', time: '09:00 PM', icon: 'bi-moon-stars-fill' },
];

export function buildSeatLayout(vehicleType: SharedVehicleType, bookedSeatIds: string[] = []): Seat[] {
  const rowSizes: Record<SharedVehicleType, number[]> = {
    '4-seater': [2, 2],
    '6-seater': [2, 2, 2],
    '7-seater': [2, 2, 3],
  };

  const rowLabels = ['A', 'B', 'C', 'D'];
  const seats: Seat[] = [];

  rowSizes[vehicleType].forEach((seatCount, rowIndex) => {
    const row = rowLabels[rowIndex];
    for (let position = 1; position <= seatCount; position++) {
      const id = `${row}${position}`;
      seats.push({
        id,
        row,
        position,
        status: bookedSeatIds.includes(id) ? 'booked' : 'available',
      });
    }
  });

  return seats;
}

/** Sample shared cabs used to power the "Shared Cab" tab. */
export const MOCK_SHARED_CABS: SharedCab[] = [
  {
    id: 'sc-101',
    cabNumber: 'SH-101',
    vehicleName: 'Toyota Innova',
    vehicleType: '6-seater',
    driverName: 'Ravi Kumar',
    departureTime: '09:30 AM',
    totalSeats: 6,
    availableSeats: 4,
    farePerSeat: 450,
    rating: 4.6,
    seats: buildSeatLayout('6-seater', ['A2', 'C1']),
    distanceFromUser: 1.8,
    directionFromUser: 'North-East',
    startTime: '08:45 AM',
    nearestPickupPoint: 'Metro Station Gate 1',
    reachPickupTime: '09:15 AM',
  },
  {
    id: 'sc-102',
    cabNumber: 'SH-102',
    vehicleName: 'Maruti Ertiga',
    vehicleType: '6-seater',
    driverName: 'Suresh Reddy',
    departureTime: '05:15 PM',
    totalSeats: 6,
    availableSeats: 2,
    farePerSeat: 400,
    rating: 4.3,
    seats: buildSeatLayout('6-seater', ['A1', 'A2', 'B1', 'C2']),
    distanceFromUser: 4.2,
    directionFromUser: 'South',
    startTime: '04:30 PM',
    nearestPickupPoint: 'City Mall Main Entrance',
    reachPickupTime: '05:00 PM',
  },
  {
    id: 'sc-103',
    cabNumber: 'SH-103',
    vehicleName: 'Honda Amaze',
    vehicleType: '4-seater',
    driverName: 'Anil Sharma',
    departureTime: '06:30 PM',
    totalSeats: 4,
    availableSeats: 3,
    farePerSeat: 350,
    rating: 4.8,
    seats: buildSeatLayout('4-seater', ['B2']),
    distanceFromUser: 6.5,
    directionFromUser: 'West',
    startTime: '05:45 PM',
    nearestPickupPoint: 'Central Park West Gate',
    reachPickupTime: '06:15 PM',
  },
  {
    id: 'sc-104',
    cabNumber: 'SH-104',
    vehicleName: 'Mahindra Xylo',
    vehicleType: '7-seater',
    driverName: 'Prakash Iyer',
    departureTime: '08:00 PM',
    totalSeats: 7,
    availableSeats: 5,
    farePerSeat: 380,
    rating: 4.4,
    seats: buildSeatLayout('7-seater', ['C1', 'C3']),
    distanceFromUser: 8.9,
    directionFromUser: 'North-West',
    startTime: '07:15 PM',
    nearestPickupPoint: 'Airport Terminal 2 Arrivals',
    reachPickupTime: '07:45 PM',
  },
  {
    id: 'sc-105',
    cabNumber: 'SH-105',
    vehicleName: 'Hyundai Creta',
    vehicleType: '4-seater',
    driverName: 'Vikram Singh',
    departureTime: '02:30 PM',
    totalSeats: 4,
    availableSeats: 2,
    farePerSeat: 420,
    rating: 4.5,
    seats: buildSeatLayout('4-seater', ['A1', 'B1']),
    distanceFromUser: 3.1,
    directionFromUser: 'North',
    startTime: '01:45 PM',
    nearestPickupPoint: 'Metro Pillar 120',
    reachPickupTime: '02:15 PM',
  },
  {
    id: 'sc-106',
    cabNumber: 'SH-106',
    vehicleName: 'Kia Carens',
    vehicleType: '7-seater',
    driverName: 'Harish Patil',
    departureTime: '09:45 PM',
    totalSeats: 7,
    availableSeats: 4,
    farePerSeat: 460,
    rating: 4.7,
    seats: buildSeatLayout('7-seater', ['A2', 'B2', 'C1']),
    distanceFromUser: 5.4,
    directionFromUser: 'East',
    startTime: '09:00 PM',
    nearestPickupPoint: 'Tech Hub Gate 4',
    reachPickupTime: '09:30 PM',
  },
  {
    id: 'sc-107',
    cabNumber: 'SH-107',
    vehicleName: 'Tata Altroz',
    vehicleType: '4-seater',
    driverName: 'Rajesh Yadav',
    departureTime: '05:45 PM',
    totalSeats: 4,
    availableSeats: 3,
    farePerSeat: 330,
    rating: 4.9,
    seats: buildSeatLayout('4-seater', ['A2']),
    distanceFromUser: 1.2,
    directionFromUser: 'South-East',
    startTime: '05:00 PM',
    nearestPickupPoint: 'Corner Coffee House',
    reachPickupTime: '05:30 PM',
  },
  {
    id: 'sc-108',
    cabNumber: 'SH-108',
    vehicleName: 'Toyota Fortuner',
    vehicleType: '7-seater',
    driverName: 'Amit Mishra',
    departureTime: '05:15 PM',
    totalSeats: 7,
    availableSeats: 6,
    farePerSeat: 500,
    rating: 4.8,
    seats: buildSeatLayout('7-seater', ['B3']),
    distanceFromUser: 2.1,
    directionFromUser: 'North-West',
    startTime: '05:30 PM',
    nearestPickupPoint: 'Railway Station Exit 2',
    reachPickupTime: '05:45 PM',
  },
  {
    id: 'sc-109',
    cabNumber: 'SH-109',
    vehicleName: 'Maruti Swift',
    vehicleType: '4-seater',
    driverName: 'Gaurav Saxena',
    departureTime: '03:45 PM',
    totalSeats: 4,
    availableSeats: 2,
    farePerSeat: 320,
    rating: 4.2,
    seats: buildSeatLayout('4-seater', ['A2', 'B1']),
    distanceFromUser: 5.7,
    directionFromUser: 'East',
    startTime: '03:15 PM',
    nearestPickupPoint: 'Sector 62 Metro Pillar 54',
    reachPickupTime: '03:30 PM',
  },
  {
    id: 'sc-110',
    cabNumber: 'SH-110',
    vehicleName: 'Mahindra Scorpio',
    vehicleType: '7-seater',
    driverName: 'Sandeep Singh',
    departureTime: '10:30 PM',
    totalSeats: 7,
    availableSeats: 5,
    farePerSeat: 440,
    rating: 4.5,
    seats: buildSeatLayout('7-seater', ['C1', 'C2']),
    distanceFromUser: 7.3,
    directionFromUser: 'South-West',
    startTime: '09:45 PM',
    nearestPickupPoint: 'Grand Plaza Hotel Gate 1',
    reachPickupTime: '10:15 PM',
  },
];
